"""added firebase_id column to User table

Revision ID: 726b619a11e3
Revises: 083f633c24ed
Create Date: 2024-07-02 21:19:03.126899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726b619a11e3'
down_revision: Union[str, None] = '083f633c24ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['firebase_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'firebase_id')
    # ### end Alembic commands ###
