"""goal_title_duedate

Revision ID: 7d83a97af5cf
Revises: 9cc6a69e7146
Create Date: 2024-06-20 16:37:46.960444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d83a97af5cf'
down_revision: Union[str, None] = '9cc6a69e7146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('title', sa.String(), nullable=False))
    op.add_column('goals', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'due_date')
    op.drop_column('goals', 'title')
    # ### end Alembic commands ###
