"""goal_title_duedate

Revision ID: 7d83a97af5cf
Revises: 9cc6a69e7146
Create Date: 2024-06-20 16:37:46.960444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d83a97af5cf'
down_revision: Union[str, None] = '9cc6a69e7146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('title', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))


    # Update existing rows with the default value
    op.execute("UPDATE goals SET title = 'Default Title' WHERE title IS NULL")
    op.execute("UPDATE goals SET due_date = '2024-12-31' WHERE due_date IS NULL")
    

    # Alter the column to be non-nullable if needed
    op.alter_column('goals', 'title', nullable=False)
    op.alter_column('goals', 'due_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'due_date')
    op.drop_column('goals', 'title')
    # ### end Alembic commands ###
